server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = / {
    return 302 http://$http_host/diapers_house/;
  }

  location /diapers_house/ {
    alias /usr/share/nginx/html/diapers_house/;
    index index.html;
    try_files $uri $uri/ /diapers_house/index.html;
  }
}
